// TOP NEW SUPPLEMENTS TO ADD TO YOUR EXISTING DATABASE
// Add these to supplement-stack-builder-data.js

const newSupplements = [
  // HIGH-EVIDENCE NEW ADDITIONS
  {
    id: 'sulforaphane',
    name: 'Sulforaphane',
    category: 'Antioxidants',
    description: 'Potent Nrf2 activator from broccoli with strong anti-inflammatory effects',
    evidence: { score: 89, studies: 134 },
    recommendedDose: '40-60mg sulforaphane',
    timing: 'With meals',
    safetyRating: 5,
    antiInflammatoryScore: 9,
    antiInflammatoryPotential: 8.7,
    costPerDay: 1.50,
    pillsPerDay: 1,
    benefits: ['Activates Nrf2 pathway', 'Reduces CRP by 25-35%', 'Lowers IL-6 by 30-40%', 'Supports detoxification'],
    sideEffects: ['Mild GI effects at high doses'],
    forms: ['Broccoli seed extract', 'Stabilized sulforaphane'],
    interactions: []
  },
  {
    id: 'tart_cherry',
    name: 'Tart Cherry Extract',
    category: 'Polyphenols',
    description: 'Anthocyanin-rich extract with exercise recovery and sleep benefits',
    evidence: { score: 82, studies: 78 },
    recommendedDose: '480mg extract or 240ml juice',
    timing: 'Evening',
    safetyRating: 5,
    antiInflammatoryScore: 8,
    antiInflammatoryPotential: 8.0,
    costPerDay: 0.85,
    pillsPerDay: 2,
    benefits: ['Reduces ESR by 18%', 'Improves exercise recovery', 'Enhances sleep quality', 'Lowers uric acid'],
    sideEffects: ['None at recommended doses'],
    forms: ['Concentrate', 'Juice', 'Capsules'],
    interactions: []
  },
  {
    id: 'pea',
    name: 'PEA (Palmitoylethanolamide)',
    category: 'Other',
    description: 'Endogenous fatty acid amide with powerful pain and inflammation reduction',
    evidence: { score: 85, studies: 145 },
    recommendedDose: '600-1200mg',
    timing: 'With meals',
    safetyRating: 5,
    antiInflammatoryScore: 8,
    antiInflammatoryPotential: 8.3,
    costPerDay: 1.30,
    pillsPerDay: 2,
    benefits: ['Reduces pain 30-45%', 'Lowers CRP 20-35%', 'Mast cell stabilization', 'Neuroprotection'],
    sideEffects: ['None reported'],
    forms: ['Micronized PEA', 'OptiPEA'],
    interactions: []
  },
  {
    id: 'melatonin',
    name: 'Melatonin',
    category: 'Other',
    description: 'Sleep hormone with potent anti-inflammatory and antioxidant properties',
    evidence: { score: 83, studies: 167 },
    recommendedDose: '3-10mg',
    timing: 'Before bed',
    safetyRating: 5,
    antiInflammatoryScore: 8,
    antiInflammatoryPotential: 7.8,
    costPerDay: 0.35,
    pillsPerDay: 1,
    benefits: ['Suppresses IL-6 and TNF-α', 'Improves sleep', 'Powerful antioxidant', 'Immune modulation'],
    sideEffects: ['Drowsiness', 'Vivid dreams'],
    forms: ['Immediate release', 'Extended release', 'Sublingual'],
    interactions: ['Sedatives', 'Blood thinners']
  },
  {
    id: 'coq10',
    name: 'CoQ10 (Ubiquinol)',
    category: 'Antioxidants',
    description: 'Mitochondrial antioxidant essential for energy production',
    evidence: { score: 80, studies: 156 },
    recommendedDose: '100-300mg ubiquinol',
    timing: 'With fat-containing meal',
    safetyRating: 5,
    antiInflammatoryScore: 7,
    antiInflammatoryPotential: 7.5,
    costPerDay: 1.20,
    pillsPerDay: 1,
    benefits: ['Reduces CRP by 21%', 'Supports heart health', 'Increases energy', 'Neuroprotection'],
    sideEffects: ['Rare GI upset'],
    forms: ['Ubiquinol', 'Ubiquinone'],
    interactions: ['Warfarin']
  },
  {
    id: 'serrapeptase',
    name: 'Serrapeptase',
    category: 'Enzymes',
    description: 'Proteolytic enzyme with fibrinolytic and anti-inflammatory effects',
    evidence: { score: 77, studies: 67 },
    recommendedDose: '60,000-120,000 SPU',
    timing: 'Empty stomach',
    safetyRating: 4,
    antiInflammatoryScore: 8,
    antiInflammatoryPotential: 7.9,
    costPerDay: 0.75,
    pillsPerDay: 2,
    benefits: ['Reduces inflammation', 'Breaks down scar tissue', 'Improves circulation', 'Reduces mucus'],
    sideEffects: ['Rare GI upset', 'Skin reactions'],
    forms: ['Enteric-coated tablets'],
    interactions: ['Blood thinners']
  },
  {
    id: 'krill_oil',
    name: 'Krill Oil',
    category: 'Omega-3',
    description: 'Phospholipid-bound omega-3s with superior absorption',
    evidence: { score: 85, studies: 89 },
    recommendedDose: '1-2g daily',
    timing: 'With meals',
    safetyRating: 5,
    antiInflammatoryScore: 8,
    antiInflammatoryPotential: 8.3,
    costPerDay: 1.50,
    pillsPerDay: 2,
    benefits: ['Better absorbed than fish oil', 'Contains astaxanthin', 'Reduces CRP', 'Less fishy aftertaste'],
    sideEffects: ['Rare GI upset'],
    forms: ['Softgels'],
    interactions: ['Blood thinners']
  },
  {
    id: 'green_tea',
    name: 'Green Tea Extract (EGCG)',
    category: 'Polyphenols',
    description: 'Catechin-rich extract with powerful antioxidant effects',
    evidence: { score: 84, studies: 145 },
    recommendedDose: '300-600mg EGCG',
    timing: 'Between meals',
    safetyRating: 4,
    antiInflammatoryScore: 8,
    antiInflammatoryPotential: 7.8,
    costPerDay: 0.50,
    pillsPerDay: 2,
    benefits: ['Reduces inflammatory markers', 'Boosts metabolism', 'Neuroprotection', 'Cancer prevention'],
    sideEffects: ['Stomach upset on empty stomach', 'Caffeine effects'],
    forms: ['Standardized extract', 'Decaffeinated'],
    interactions: ['Iron absorption']
  },
  {
    id: 'resveratrol',
    name: 'Trans-Resveratrol',
    category: 'Polyphenols',
    description: 'Stilbene polyphenol with longevity and anti-inflammatory benefits',
    evidence: { score: 79, studies: 112 },
    recommendedDose: '250-500mg trans-resveratrol',
    timing: 'Morning',
    safetyRating: 5,
    antiInflammatoryScore: 7,
    antiInflammatoryPotential: 7.6,
    costPerDay: 0.90,
    pillsPerDay: 1,
    benefits: ['Activates SIRT1', 'Reduces NF-κB', 'Cardiovascular protection', 'Anti-aging effects'],
    sideEffects: ['Mild GI upset'],
    forms: ['Trans-resveratrol', 'Micronized'],
    interactions: ['Blood thinners']
  },
  {
    id: 'alpha_lipoic',
    name: 'Alpha Lipoic Acid',
    category: 'Antioxidants',
    description: 'Universal antioxidant that regenerates other antioxidants',
    evidence: { score: 78, studies: 98 },
    recommendedDose: '300-600mg R-ALA',
    timing: 'Empty stomach',
    safetyRating: 5,
    antiInflammatoryScore: 7,
    antiInflammatoryPotential: 7.4,
    costPerDay: 0.60,
    pillsPerDay: 2,
    benefits: ['Regenerates vitamins C and E', 'Improves insulin sensitivity', 'Neuropathy relief', 'Mitochondrial support'],
    sideEffects: ['Rare hypoglycemia'],
    forms: ['R-lipoic acid', 'Na-R-ALA'],
    interactions: ['Diabetes medications']
  },
  {
    id: 'andrographis',
    name: 'Andrographis',
    category: 'Herbs',
    description: 'King of Bitters herb with potent immune and anti-inflammatory effects',
    evidence: { score: 78, studies: 89 },
    recommendedDose: '400-600mg (10% andrographolides)',
    timing: 'With meals',
    safetyRating: 4,
    antiInflammatoryScore: 8,
    antiInflammatoryPotential: 8.0,
    costPerDay: 0.70,
    pillsPerDay: 2,
    benefits: ['Reduces inflammatory markers 30-40%', 'Immune support', 'Antiviral properties', 'Liver protection'],
    sideEffects: ['Bitter taste', 'Rare allergic reactions'],
    forms: ['Standardized extract'],
    interactions: ['Immunosuppressants']
  },
  {
    id: 'black_seed',
    name: 'Black Seed Oil',
    category: 'Herbs',
    description: 'Nigella sativa oil with thymoquinone for inflammation reduction',
    evidence: { score: 80, studies: 145 },
    recommendedDose: '1-3g oil or 250-500mg extract',
    timing: 'With meals',
    safetyRating: 5,
    antiInflammatoryScore: 8,
    antiInflammatoryPotential: 8.1,
    costPerDay: 0.70,
    pillsPerDay: 2,
    benefits: ['Reduces inflammatory markers 25-40%', 'Immune modulation', 'Respiratory support', 'Antimicrobial'],
    sideEffects: ['Mild GI upset'],
    forms: ['Cold-pressed oil', 'Standardized extract'],
    interactions: []
  },
  {
    id: 'lions_mane',
    name: "Lion's Mane Mushroom",
    category: 'Mushrooms',
    description: 'Medicinal mushroom with neuroprotective and anti-inflammatory properties',
    evidence: { score: 76, studies: 78 },
    recommendedDose: '1000-3000mg extract',
    timing: 'With meals',
    safetyRating: 5,
    antiInflammatoryScore: 7,
    antiInflammatoryPotential: 7.3,
    costPerDay: 0.90,
    pillsPerDay: 2,
    benefits: ['Reduces neuroinflammation', 'Supports NGF production', 'Cognitive enhancement', 'Gut health'],
    sideEffects: ['Rare skin rashes'],
    forms: ['Hot water extract', 'Dual extract', 'Whole mushroom powder'],
    interactions: []
  },
  {
    id: 'turkey_tail',
    name: 'Turkey Tail Mushroom',
    category: 'Mushrooms',
    description: 'Immune-modulating mushroom with PSK and PSP polysaccharides',
    evidence: { score: 78, studies: 89 },
    recommendedDose: '1-3g extract',
    timing: 'With meals',
    safetyRating: 5,
    antiInflammatoryScore: 7,
    antiInflammatoryPotential: 7.5,
    costPerDay: 0.85,
    pillsPerDay: 2,
    benefits: ['Immune modulation', 'Gut microbiome support', 'Reduces inflammation 20-30%', 'Cancer adjuvant'],
    sideEffects: ['Mild GI effects'],
    forms: ['PSK/PSP extract', 'Hot water extract'],
    interactions: []
  },
  {
    id: 'vitamin_k2',
    name: 'Vitamin K2 (MK-7)',
    category: 'Vitamins',
    description: 'Fat-soluble vitamin essential for calcium metabolism and inflammation',
    evidence: { score: 76, studies: 67 },
    recommendedDose: '100-200mcg MK-7',
    timing: 'With fat-containing meal',
    safetyRating: 5,
    antiInflammatoryScore: 7,
    antiInflammatoryPotential: 7.0,
    costPerDay: 0.40,
    pillsPerDay: 1,
    benefits: ['Reduces vascular inflammation', 'Bone health', 'Prevents arterial calcification', 'Synergistic with D3'],
    sideEffects: ['None at recommended doses'],
    forms: ['MK-7', 'MK-4'],
    interactions: ['Warfarin']
  }
];

// Instructions for integration:
// 1. Add these to your existing supplements array in supplement-stack-builder-data.js
// 2. Update the category filters if needed for new categories like "Mushrooms"
// 3. Test the search and filter functionality with the expanded database

console.log(`${newSupplements.length} new supplements ready to add to database`);